version: "3.9"

services:
  web_app:
    build:
      context: .
    command: uvicorn src.main_app:app --host 0.0.0.0 --port 80 --reload
    # FOR debugging container
    # command: sleep infinity
    image: nginx_ssl_certobot_web_app
    container_name: web_app
    volumes:
      - ./src/:/usr/code/project/src/

  nginx:
    build:
      context: deploy/nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - web_app
